services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: app
    ports:
      - '8000:8000'
    environment:
      ENV: local
      DB_NAME: todoapp
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      ALLOWED_HOSTS: localhost,127.0.0.1
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app

volumes:
  postgres_data:
