[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true
