
buildpush:
	cd nginx && \
	docker build --platform linux/x86_64  -t asia-northeast1-docker.pkg.dev/gcloud-and-terraform/test/nginx:latest . && \
	docker push asia-northeast1-docker.pkg.dev/gcloud-and-terraform/test/nginx:latest