name: Python Lint

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'app/**/*.py'
      - 'app/**/requirements.txt'
      - '.github/workflows/python-lint.yml'

jobs:
  python-lint:
    name: Python Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Black (format check)
        run: |
          black --check app/app/

      - name: Run isort (import sorting check)
        run: |
          isort --check-only app/app/

      - name: Run Flake8 (linting)
        run: |
          # E501: line too long (handled by black)
          # W503: line break before binary operator (conflicts with black)
          flake8 app/app/ --max-line-length=88 --extend-ignore=E501,W503
